### ISSUE TITLE
Add output to pipe option

### ISSUE THREAD

**Issue by chrisnorthcott** [quiniouben/vban_receptor#10]
Would be nice to be able to pipe the output (whether that be via `pipe()` or stdout) so further processing can be done with programs like `sox` or similar, and from what I've gleaned of the code should be relatively simple to implement to the point I wouldn't mind taking a crack at it myself if you have other priorities.

**Comment by chrisnorthcott** [comment]
for the purposes of avoiding duplication of effort I've written a pipe backend now, just gonna play with and tweak it a bit before I submit a PR.

**Comment by quiniouben** [comment]
Hi, yes sure, it is a good idea, thank you for proposing and doing it. Just send the PR when it's ready.

**Comment by quiniouben** [comment]
Experimental Implementation done by crhisnorthcott integrated.
