### ISSUE TITLE
underrun

### ISSUE THREAD

**Issue by Bryceclark56** [quiniouben/vban_receptor#4]
While using vban receptor, I was constantly getting these errors http://goo.gl/fHAFRS. My audio was also periodically cutting out.

**Comment by quiniouben** [comment]
Thank you for your report.
It looks like you are receiving network packets slower than needed for continuous audio playing or that your network connection causes some packet loss / delays.
vban_receptor is not yet featured to investigate what would be the cause, but however, you can play with the --quality (-q) parameter and increase it up to 4 to see if it improves the situation.
Let me know if it helps.

**Comment by Bryceclark56** [comment]
Yeah, it is the connection between the devices that is the problem, thx for the help!
