### ISSUE TITLE
Build failure while trying to build it on Ubuntu 16.04 LTS...

### ISSUE THREAD

**Issue by tahiro86j** [quiniouben/vban_receptor#5]
The output I got from `make VERBOSE=1` is as follows;
`In file included from /usr/include/alsa/asoundlib.h:54:0,
                 from audio.h:23,
                 from main.c:25:
/usr/include/alsa/pcm.h:1010:15: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
 static inline void snd_pcm_pack_audio_tstamp_config(unsigned int *data,
               ^
/usr/include/alsa/pcm.h:1018:15: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
 static inline void snd_pcm_unpack_audio_tstamp_report(unsigned int data, unsigned int accuracy,
               ^
Makefile:345: recipe for target 'main.o' failed
make: *** [main.o] Error 1`

Googling suggested me that the issue has something to do with the version of compiler and I got;
`gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2)`

I believe that the necessary headers are in place.

**Comment by tahiro86j** [comment]
One of my campus-mates was clever enough to tackle the issue.
Altering
`AM_CFLAGS = -ansi -Wpedantic -Wall -Wno-multichar -O2`
in the resulting _src/Makefile_ with
`AM_CFLAGS = -std=c99 -Wpedantic -Wall -Wno-multichar -O2`
fixed it tentatively.
I hope this info is useful enough.

**Comment by quiniouben** [comment]
Hello,
Thank you for reporting the trouble. Yep, I could reach the same conclusion as your mate :).
I will update the make options ASAP.

**Comment by quiniouben** [comment]
Fixed according to proposal in tahiro86j comment.
