### ISSUE TITLE
Add native jackd support to vban_receptor (formerly: Adding option to specify the interface for output...?)

### ISSUE THREAD

**Issue by tahiro86j** [quiniouben/vban_receptor#6]
As I am using the built-binary with _jackd2_, the process uses (or must use) _PulseAudio Jack Sink_ in order to get its output over to the sound device. The problem so far is, because _PulseAudio Jack Sink_ mixes down all inputs to it, output from each instance of the _vban_receptor_ (if/when running multiple instances) cannot be identified.
If there were a command-line option to allow users to specify the sound interface through which the instance would output, that opens doors to running multiple instances of _vban_receptor_ (for multiple connections with multiple hosts), and sending output to different jack-inputs using _jack_input_, hence allowing _jack_mixer_ be used in the setup. It's not super-urgent, but would be a neat enhancement if implemented. The best is _vban_receptor_ becomes jackd-capable, but I guess that's asking for too much.

**Comment by quiniouben** [comment]
Yep, that's already in my todo-list to allow the user to choose the alsa ouput to use. It was also mentioned in #3 7th comment (currently the latest comment in #3 ). As to make vban_receptor natively jackd or PulseAudio enabled, well, that's another story, but if the demand is growing, why not.

**Comment by tahiro86j** [comment]
Well, because the _Banana_ on Windows is capable of sending outputs to ASIO interfaces, _jackd_ slave on Windows running with _JackRouter ASIO_ enabled could potentially do things similar to those potentially achieved by making the above enhancements. This _ASIO-based_ method has not been tested with my own hands, yet also has potentials to allow transmission/reception of 96kHz/24bit formats (or higher) as well.
I think that the main reason for which I believe people would want to choose _Banana_ over _jackd_ for Windows is because _jackd_ for Windows does not come with a virtual-device driver to run on Windows (and behaves like an actual sound-card).
I'm not saying jackd-capability of _vban_receptor_ won't be popular, but I am just saying because I would like that people here understand actual values of discussions and improvements taking places here.
I just thought that this is the point we could be made clearly aware of...

**Comment by quiniouben** [comment]
I just commited support for output alsa device selection.
However, I keep this issue open and change the title to keep track of the idea to implement direct jackd support into vban_receptor.

**Comment by tahiro86j** [comment]
@quiniouben Appreciations to your attitude and intention.

**Comment by quiniouben** [comment]
Jackd support is not yet implemented but I just commited support for pulseaudio, opening the door for multiple possible backends.

**Comment by quiniouben** [comment]
It took me a while, but here it is, jack support.
Beware, I made it auto connect to first jack interfaces. If it is annoying for most, I can remove or make it as an option.
